version: '3.1'

services:
  chroma:
    image: ghcr.io/chroma-core/chroma:0.4.5 # Spins up a ChromaDB instance at port 8000

  repo-query:
    image: open-sauced-repo-query:latest
    environment:
      # Consume env variables from a .env file found in the same directory
      # as this docker-compose file. See ".env.example" for more details.
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      RUST_LOG: "info"
      CHROMA_URL: "http://chroma:8000"
      WEBSERVER_PORT: ${WEBSERVER_PORT}
    depends_on:
      - chroma
    ports:
      - "${WEBSERVER_PORT}:${WEBSERVER_PORT}"
